let game=null,questions=[],qIndex=0,phase="personagem";
const phaseNames={personagem:"PERSONAGEM",eu:"EU"};
async function refreshPlayers(){if(!game)return;const {count}=await supabaseClient.from("players").select("*",{count:"exact",head:true}).eq("game_id",game.id);$("#count").textContent=`${count||0} participante${count===1?"":"s"}`}
function q(){return questions[qIndex]}
function lobby(){ $("#phaseBadge").textContent=phaseNames[phase];$("#screenContent").innerHTML=`<div class="eyebrow">PARTIDA ${escapeHtml(game.code)}</div><h1>Prontos?</h1><p class="situation">Os alunos entram com o código <strong>${escapeHtml(game.code)}</strong>.</p><div class="big-code">${escapeHtml(game.code)}</div>`}
function renderQ(){const x=q();$("#phaseBadge").textContent=`${phaseNames[phase]} · RODADA ${x.number}/8`;$("#screenContent").innerHTML=`<div class="question-number">RODADA ${x.number}</div><h1>${escapeHtml(x.title)}</h1><p class="situation">${escapeHtml(x.situation)}</p><h2 class="question-call">O que você faria?</h2><div class="options-projector">${x.options.map(o=>`<div class="projector-option"><b>${o.key}</b><span>${escapeHtml(o.text)}</span></div>`).join("")}</div>`}
function reflection(){const x=q();$("#screenContent").innerHTML=`<div class="question-number">REFLEXÃO</div><h1>${escapeHtml(x.title)}</h1><div class="reflection">${escapeHtml(x.reflection)}</div><p class="situation">Converse com a turma antes de continuar.</p>`}
async function upd(p){const {data,error}=await supabaseClient.from("games").update(p).eq("id",game.id).select().single();if(error)throw error;game=data}
async function start(ph){phase=ph;qIndex=0;await upd({status:"question",phase,question_index:0,current_question_id:questions[0].id});renderQ();$("#start").hidden=true;$("#reveal").hidden=false;$("#reflection").hidden=true;$("#next").hidden=true;$("#nextPhase").hidden=true;$("#finish").hidden=true}
async function counts(){const {data,error}=await supabaseClient.from("answers").select("option_key").eq("game_id",game.id).eq("question_id",q().id).eq("phase",phase);if(error)throw error;return data.reduce((a,x)=>(a[x.option_key]=(a[x.option_key]||0)+1,a),{})}
function showCounts(c){const x=q(),total=Object.values(c).reduce((a,b)=>a+b,0)||1;$("#screenContent").innerHTML=`<div class="question-number">RESULTADO · RODADA ${x.number}</div><h1>${escapeHtml(x.title)}</h1><div class="bars">${x.options.map(o=>{let n=c[o.key]||0,p=Math.round(n/total*100);return `<div class="bar-row"><b>${o.key}</b><div class="bar"><i style="width:${p}%"></i></div><span>${n}</span></div>`}).join("")}</div>`}
$("#create").onclick=async()=>{try{const code=$("#manualCode").value.trim().toUpperCase();game=await getGameByCode(code);questions=await getQuestions();qIndex=game.question_index||0;phase=game.phase||"personagem";$("#create").hidden=true;$("#manualCode").parentElement.hidden=true;$("#start").hidden=false;await refreshPlayers();lobby();setInterval(refreshPlayers,3000)}catch(e){console.error(e);alert("Partida não encontrada. Confira o código.")}};
$("#start").onclick=()=>start("personagem");
$("#reveal").onclick=async()=>{showCounts(await counts());await upd({status:"reveal"});$("#reveal").hidden=true;$("#reflection").hidden=false};
$("#reflection").onclick=()=>{reflection();$("#reflection").hidden=true;$("#next").hidden=false};
$("#next").onclick=async()=>{if(qIndex<questions.length-1){qIndex++;await upd({status:"question",question_index:qIndex,current_question_id:questions[qIndex].id});renderQ();$("#next").hidden=true;$("#reveal").hidden=false}else if(phase==="personagem"){$("#next").hidden=true;$("#nextPhase").hidden=false;reflection()}else{$("#next").hidden=true;$("#finish").hidden=false;reflection()}};
$("#nextPhase").onclick=()=>start("eu");
$("#finish").onclick=async()=>{await upd({status:"finished"});location.href=`resultado.html?game=${game.id}`};
